sudo: false

language: java

jdk:
  - openjdk7
  - oraclejdk8

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.m2/repository'

script:
  - mvn -B test
  - rm -rf $HOME/.m2/repository/com/threerings/vilya*
